name: Build Fiction
on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows:
      - Release (Internal)
    types:
      - completed

jobs:
  build-fiction:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build upload with tag ${{ github.ref_name }}"
