name: Build Fiction
on:
  push:
    tags:
      - '*'

jobs:
  build-fiction:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - run: echo "Build upload with tag ${{ github.ref_name }}"
