name: Release (Internal)
on:
  workflow_dispatch:
    inputs:
      release_body:
        description: 'When set, adds extra text to body.'
        required: false
        default: ''

env:
  RELEASE_REGEX_ALPHA: "^v[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+$"
  RELEASE_REGEX: "^v[0-9]+.[0-9]+.[0-9]+$"

jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get short sha
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Get latest tag
        id: get-latest-tag
        run: echo ::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Create next tag
        id: get-next-tag
        run: |
          export LATEST_TAG="${{ steps.get-latest-tag.outputs.tag }}"
          echo "Latest tag is: ${LATEST_TAG}"

          source ./bash.sh

          export NEW_TAG=$(get_new_tag ${LATEST_TAG})
          echo "New tag is: ${NEW_TAG}"

          echo ::set-output name=tag::${NEW_TAG}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ steps.get-next-tag.outputs.tag }}"
          message: "${{ github.event.inputs.release_body }}"
