name: Release (Internal)
on:
  workflow_dispatch:
    inputs:
      release_body:
        description: 'When set, adds extra text to body.'
        required: false
        default: ''

jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          persist-credentials: false

      - name: Get short sha
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Create next tag
        id: get-next-tag
        run: |
          export LATEST_TAG="${{ steps.get-latest-tag.outputs.tag }}"
          echo "Latest tag is: ${LATEST_TAG}"

          source ./bash.sh

          export NEW_TAG=$(release_internal ${LATEST_TAG})
          echo "New tag is: ${NEW_TAG}"

          echo ::set-output name=tag::${NEW_TAG}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ steps.get-next-tag.outputs.tag }}"
          message: "${{ github.event.inputs.release_body }}"
          github_token: ${{ secrets.PA_TOKEN }}

      - name: Create release notes
        if: ${{ github.event.inputs.create_release_notes != "n" }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get-next-tag.outputs.tag }}
          release_name: ${{ steps.get-next-tag.outputs.tag }}
          draft: true
          prerelease: false
