name: Increment release candidate
on:
  workflow_dispatch:
    inputs: {}

jobs:
  create-tag-and-release:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get short sha
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Extract branch name
        id: get-current-branch
        run: echo ::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})

      - name: Create next release candidate tag
        id: get-next-tag
        run: |
          export LATEST_TAG="${{ steps.get-latest-tag.outputs.tag }}"
          echo "Latest tag is: ${LATEST_TAG}"

          export CURRENT_BRANCH="${{ steps.get-current-branch.outputs.branch }}"
          echo "Current branch is: ${CURRENT_BRANCH}"

          source ./bash.sh

          export NEW_TAG=$(release_candidate ${LATEST_TAG} ${CURRENT_BRANCH})
          echo "New tag is: ${NEW_TAG}"

          echo ::set-output name=tag::${NEW_TAG}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ steps.get-next-tag.outputs.tag }}"
          message: "${{ github.event.inputs.release_body }}"
          commit_sha: "${{ steps.short-sha.outputs.sha }}"
