name: Release (On merge release-)
on:
  workflow_dispatch:
    inputs:
      release_body:
        description: 'When set, adds extra text to body.'
        required: false
        default: ''


jobs:
  create-final-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2